### ISSUE TITLE
Voidfang Vestments incorrectly listed with "Double Grenade"

### ISSUE THREAD

**Issue by kyleshay** [DestinyTrialsReport/DestinyTrialsReport#114] opened 2015-11-16 05:18 UTC
![screenshot 2015-11-16 at 00 15 57](https://cloud.githubusercontent.com/assets/424158/11174771/559c4176-8bf7-11e5-98b2-61432181f672.png)

> Your Axion Bolt grenade spawns an additional seeker. Respawn with full grenade energy.

**Comment by SteffanLong** [comment] 2015-11-16 05:24
Good find. Thanks!

**Comment by SteffanLong** [comment] 2015-11-16 05:58
Can you please provide the PSN/XBL gamertag you used to find this? It seems likely that they are currently on Sunsinger with the double grenade perk. I'm unable to reproduce with just the Voidfang Vestments on.

**Comment by kyleshay** [comment] 2015-11-16 06:28
Noticed it on my voidwalker. 

Xbox one,

> v DontCare v

**Comment by SteffanLong** [comment] 2015-11-16 07:13
Ah, yes. I found the issue. It will be fixed in the next build. Thank you!

**Comment by SteffanLong** [comment] 2015-11-16 08:28
Fixed in 591857.

**Closed by SteffanLong** 2015-11-16 08:28 UTC
